/* ===================================================
   VOWEL QUEST — 100 Question Bank
   Reorganized into 3 Levels (5 random picked each play)
   Each question: word, emoji, vowels, consonants
   =================================================== */

const LEVELS = [
  {
    id: 1,
    name: "Castle Gate",
    emoji: "🚪",
    description: "Simple words guard the entrance.",
    introStory: "You arrive at the gates of the Enchanted Castle. The ancient guardians have sealed the entrance with word magic! Prove your knowledge of letters to pass through. Your fairy companion flutters beside you, ready to help!",
    completeStory: "The Castle Gate groans open! Torches flicker to life along the corridor. Your letter knowledge has impressed the ancient guardians. You find a magic key glowing on the floor!",
    loot: "🗝️",
    bg: "#1a0a40"
  },
  {
    id: 2,
    name: "Dragon's Lair",
    emoji: "🐉",
    description: "Face the dragon's riddle of words.",
    introStory: "Beyond the gate, a great dragon coils around its treasure hoard. Its golden eyes gleam with ancient intelligence. 'Answer my word riddles,' it rumbles, 'and I shall let you pass to the Dark Sorcerer's tower!'",
    completeStory: "The dragon bows its great head in respect. 'You are worthy,' it says, and moves aside to reveal a golden door. It grants you a dragon scale of protection!",
    loot: "🐲",
    bg: "#2a1000"
  },
  {
    id: 3,
    name: "Dark Sorcerer",
    emoji: "🧙‍♂️",
    description: "⚡ BOSS BATTLE — Beat the timer!",
    introStory: "The Dark Sorcerer appears in a flash of dark lightning! 'Foolish knight!' he cackles. 'You will NEVER restore the letters to this kingdom!' His dark magic creates a time vortex — you must defeat him before time runs out!",
    completeStory: "The Dark Sorcerer screams as his power shatters! Light floods through every window of the castle as letters flow back into every word in the kingdom. You have saved the Kingdom of Letters!",
    loot: "👑",
    bg: "#1a0008",
    isBoss: true,
    timerSeconds: 90
  }
];

/* Pool of 100 questions — each has vowels AND consonants for both modes */
const QUESTIONS = [
  // ---- Easy / Level 1 pool (id 1-40) ----
  { id:1,   level:1, word:"CAT",     emoji:"🐱", vowels:["A"],        consonants:["C","T"],       hint:"A furry pet that purrs" },
  { id:2,   level:1, word:"DOG",     emoji:"🐕", vowels:["O"],        consonants:["D","G"],       hint:"Man's best friend" },
  { id:3,   level:1, word:"SUN",     emoji:"☀️",  vowels:["U"],        consonants:["S","N"],       hint:"It shines in the sky" },
  { id:4,   level:1, word:"BED",     emoji:"🛏️",  vowels:["E"],        consonants:["B","D"],       hint:"You sleep here" },
  { id:5,   level:1, word:"PIG",     emoji:"🐷", vowels:["I"],        consonants:["P","G"],       hint:"A pink farm animal" },
  { id:6,   level:1, word:"CUP",     emoji:"☕",  vowels:["U"],        consonants:["C","P"],       hint:"You drink from it" },
  { id:7,   level:1, word:"HAT",     emoji:"🎩", vowels:["A"],        consonants:["H","T"],       hint:"Worn on your head" },
  { id:8,   level:1, word:"BUS",     emoji:"🚌", vowels:["U"],        consonants:["B","S"],       hint:"A large vehicle" },
  { id:9,   level:1, word:"PEN",     emoji:"🖊️",  vowels:["E"],        consonants:["P","N"],       hint:"Used for writing" },
  { id:10,  level:1, word:"FIN",     emoji:"🦈", vowels:["I"],        consonants:["F","N"],       hint:"A fish uses this to swim" },
  { id:11,  level:1, word:"TREE",    emoji:"🌳", vowels:["E"],        consonants:["T","R"],       hint:"It has leaves and branches" },
  { id:12,  level:1, word:"ROSE",    emoji:"🌹", vowels:["O","E"],    consonants:["R","S"],       hint:"A beautiful flower" },
  { id:13,  level:1, word:"BIRD",    emoji:"🐦", vowels:["I"],        consonants:["B","R","D"],   hint:"It flies in the sky" },
  { id:14,  level:1, word:"FROG",    emoji:"🐸", vowels:["O"],        consonants:["F","R","G"],   hint:"It says ribbit" },
  { id:15,  level:1, word:"FISH",    emoji:"🐟", vowels:["I"],        consonants:["F","S","H"],   hint:"It lives in water" },
  { id:16,  level:1, word:"LEAF",    emoji:"🍃", vowels:["E","A"],    consonants:["L","F"],       hint:"Grows on a tree branch" },
  { id:17,  level:1, word:"SEED",    emoji:"🌱", vowels:["E"],        consonants:["S","D"],       hint:"Plant this to grow something" },
  { id:18,  level:1, word:"ROCK",    emoji:"🪨", vowels:["O"],        consonants:["R","C","K"],   hint:"A hard natural object" },
  { id:19,  level:1, word:"VINE",    emoji:"🌿", vowels:["I","E"],    consonants:["V","N"],       hint:"A climbing plant" },
  { id:20,  level:1, word:"POND",    emoji:"�️", vowels:["O"],        consonants:["P","N","D"],   hint:"A small body of water" },
  { id:21,  level:1, word:"CAKE",    emoji:"🎂", vowels:["A","E"],    consonants:["C","K"],       hint:"A sweet birthday treat" },
  { id:22,  level:1, word:"RICE",    emoji:"🍚", vowels:["I","E"],    consonants:["R","C"],       hint:"A grain eaten worldwide" },
  { id:23,  level:1, word:"SOUP",    emoji:"🍲", vowels:["O","U"],    consonants:["S","P"],       hint:"A warm liquid food" },
  { id:24,  level:1, word:"MILK",    emoji:"🥛", vowels:["I"],        consonants:["M","L","K"],   hint:"A white drink from cows" },
  { id:25,  level:1, word:"MEAT",    emoji:"🥩", vowels:["E","A"],    consonants:["M","T"],       hint:"Protein from animals" },
  { id:26,  level:1, word:"BOOK",    emoji:"📚", vowels:["O"],        consonants:["B","K"],       hint:"You read this" },
  { id:27,  level:1, word:"MOON",    emoji:"🌙", vowels:["O"],        consonants:["M","N"],       hint:"Glows in the night sky" },
  { id:28,  level:1, word:"STAR",    emoji:"⭐",  vowels:["A"],        consonants:["S","T","R"],   hint:"Twinkles in the sky" },
  { id:29,  level:1, word:"GOAT",    emoji:"🐐", vowels:["O","A"],    consonants:["G","T"],       hint:"A farm animal with a beard" },
  { id:30,  level:1, word:"BELL",    emoji:"🔔", vowels:["E"],        consonants:["B","L"],       hint:"It goes ding-dong" },
  { id:31,  level:1, word:"DUCK",    emoji:"🦆", vowels:["U"],        consonants:["D","C","K"],   hint:"Quacks and swims" },
  { id:32,  level:1, word:"NEST",    emoji:"🪹", vowels:["E"],        consonants:["N","S","T"],   hint:"A bird's home" },
  { id:33,  level:1, word:"RAIN",    emoji:"🌧️",  vowels:["A","I"],    consonants:["R","N"],       hint:"Falls from clouds" },
  { id:34,  level:1, word:"BOAT",    emoji:"⛵",  vowels:["O","A"],    consonants:["B","T"],       hint:"Floats on water" },
  { id:35,  level:1, word:"KITE",    emoji:"🪁", vowels:["I","E"],    consonants:["K","T"],       hint:"Flies with the wind" },
  { id:36,  level:1, word:"DRUM",    emoji:"🥁", vowels:["U"],        consonants:["D","R","M"],   hint:"A musical instrument you hit" },
  { id:37,  level:1, word:"GIFT",    emoji:"🎁", vowels:["I"],        consonants:["G","F","T"],   hint:"A wrapped present" },
  { id:38,  level:1, word:"LAMP",    emoji:"💡", vowels:["A"],        consonants:["L","M","P"],   hint:"Gives off light" },
  { id:39,  level:1, word:"RING",    emoji:"💍", vowels:["I"],        consonants:["R","N","G"],   hint:"Worn on a finger" },
  { id:40,  level:1, word:"HAND",    emoji:"✋",  vowels:["A"],        consonants:["H","N","D"],   hint:"You wave with this" },

  // ---- Medium / Level 2 pool (id 41-80) ----
  { id:41,  level:2, word:"SWORD",   emoji:"⚔️",  vowels:["O"],        consonants:["S","W","R","D"],   hint:"A long sharp blade" },
  { id:42,  level:2, word:"SHIELD",  emoji:"🛡️",  vowels:["I","E"],    consonants:["S","H","L","D"],   hint:"Blocks attacks" },
  { id:43,  level:2, word:"ARMOR",   emoji:"🪖", vowels:["A","O"],    consonants:["R","M"],           hint:"Metal body protection" },
  { id:44,  level:2, word:"LANCE",   emoji:"🗡️",  vowels:["A","E"],    consonants:["L","N","C"],       hint:"A long jousting weapon" },
  { id:45,  level:2, word:"ARROW",   emoji:"🏹", vowels:["A","O"],    consonants:["R","W"],           hint:"Shot from a bow" },
  { id:46,  level:2, word:"BLADE",   emoji:"🔪", vowels:["A","E"],    consonants:["B","L","D"],       hint:"The sharp edge of a weapon" },
  { id:47,  level:2, word:"HORSE",   emoji:"🐴", vowels:["O","E"],    consonants:["H","R","S"],       hint:"A knight rides this" },
  { id:48,  level:2, word:"BRAVE",   emoji:"💪", vowels:["A","E"],    consonants:["B","R","V"],       hint:"Having courage" },
  { id:49,  level:2, word:"STONE",   emoji:"🪨", vowels:["O","E"],    consonants:["S","T","N"],       hint:"A piece of rock" },
  { id:50,  level:2, word:"FLAME",   emoji:"🔥", vowels:["A","E"],    consonants:["F","L","M"],       hint:"Fire's dancing light" },
  { id:51,  level:2, word:"SNAKE",   emoji:"🐍", vowels:["A","E"],    consonants:["S","N","K"],       hint:"A slithering reptile" },
  { id:52,  level:2, word:"CHAIN",   emoji:"⛓️",  vowels:["A","I"],    consonants:["C","H","N"],       hint:"Metal links connected" },
  { id:53,  level:2, word:"GHOST",   emoji:"👻", vowels:["O"],        consonants:["G","H","S","T"],   hint:"A spooky spirit" },
  { id:54,  level:2, word:"TORCH",   emoji:"🪔", vowels:["O"],        consonants:["T","R","C","H"],   hint:"Portable light source" },
  { id:55,  level:2, word:"SPELL",   emoji:"🪄", vowels:["E"],        consonants:["S","P","L"],       hint:"Words of magic" },
  { id:56,  level:2, word:"RUNE",    emoji:"🔮", vowels:["U","E"],    consonants:["R","N"],           hint:"An ancient magical symbol" },
  { id:57,  level:2, word:"SMOKE",   emoji:"💨", vowels:["O","E"],    consonants:["S","M","K"],       hint:"Comes from fire" },
  { id:58,  level:2, word:"DRAGON",  emoji:"🐉", vowels:["A","O"],    consonants:["D","R","G","N"],   hint:"A fire-breathing beast" },
  { id:59,  level:2, word:"SCALE",   emoji:"🐲", vowels:["A","E"],    consonants:["S","C","L"],       hint:"Covers a dragon's body" },
  { id:60,  level:2, word:"CLAW",    emoji:"🐾", vowels:["A"],        consonants:["C","L","W"],       hint:"A sharp curved nail" },
  { id:61,  level:2, word:"FIRE",    emoji:"🔥", vowels:["I","E"],    consonants:["F","R"],           hint:"Hot and bright" },
  { id:62,  level:2, word:"GOLD",    emoji:"🪙", vowels:["O"],        consonants:["G","L","D"],       hint:"A precious yellow metal" },
  { id:63,  level:2, word:"JEWEL",   emoji:"💎", vowels:["E"],        consonants:["J","W","L"],       hint:"A precious stone" },
  { id:64,  level:2, word:"CROWN",   emoji:"👑", vowels:["O"],        consonants:["C","R","W","N"],   hint:"Worn by a king or queen" },
  { id:65,  level:2, word:"THRONE",  emoji:"🪑", vowels:["O","E"],    consonants:["T","H","R","N"],   hint:"A royal seat" },
  { id:66,  level:2, word:"QUEEN",   emoji:"👸", vowels:["U","E"],    consonants:["Q","N"],           hint:"A female ruler" },
  { id:67,  level:2, word:"PRINCE",  emoji:"🤴", vowels:["I","E"],    consonants:["P","R","N","C"],   hint:"Son of a king" },
  { id:68,  level:2, word:"CASTLE",  emoji:"�", vowels:["A","E"],    consonants:["C","S","T","L"],   hint:"A fortified building" },
  { id:69,  level:2, word:"NOBLE",   emoji:"🦚", vowels:["O","E"],    consonants:["N","B","L"],       hint:"Of high birth" },
  { id:70,  level:2, word:"FEAST",   emoji:"🍽️",  vowels:["E","A"],    consonants:["F","S","T"],       hint:"A grand celebration meal" },
  { id:71,  level:2, word:"PEARL",   emoji:"🦪", vowels:["E","A"],    consonants:["P","R","L"],       hint:"Found inside an oyster" },
  { id:72,  level:2, word:"CAVE",    emoji:"🕳️",  vowels:["A","E"],    consonants:["C","V"],           hint:"A natural underground space" },
  { id:73,  level:2, word:"WINGS",   emoji:"🦅", vowels:["I"],        consonants:["W","N","G","S"],   hint:"Used for flying" },
  { id:74,  level:2, word:"MUSIC",   emoji:"🎵", vowels:["U","I"],    consonants:["M","S","C"],       hint:"Sound arranged in melody" },
  { id:75,  level:2, word:"SKULL",   emoji:"💀", vowels:["U"],        consonants:["S","K","L"],       hint:"Head bones" },
  { id:76,  level:2, word:"APPLE",   emoji:"🍎", vowels:["A","E"],    consonants:["P","L"],           hint:"A crunchy red fruit" },
  { id:77,  level:2, word:"TOAST",   emoji:"🍞", vowels:["O","A"],    consonants:["T","S"],           hint:"Crispy browned bread" },
  { id:78,  level:2, word:"PLATE",   emoji:"🍽️",  vowels:["A","E"],    consonants:["P","L","T"],       hint:"You put food on it" },
  { id:79,  level:2, word:"CLOCK",   emoji:"🕐", vowels:["O"],        consonants:["C","L","K"],       hint:"It tells the time" },
  { id:80,  level:2, word:"GLOBE",   emoji:"🌍", vowels:["O","E"],    consonants:["G","L","B"],       hint:"A model of the Earth" },

  // ---- Hard / Level 3 Boss pool (id 81-100) ----
  { id:81,  level:3, word:"SORCERER",  emoji:"🧙‍♂️", vowels:["O","E"],        consonants:["S","R","C"],         hint:"An evil magic user" },
  { id:82,  level:3, word:"ULTIMATE",  emoji:"💫",  vowels:["U","I","A","E"], consonants:["L","T","M"],         hint:"The greatest of all" },
  { id:83,  level:3, word:"ENCHANT",   emoji:"✨",  vowels:["E","A"],         consonants:["N","C","H","T"],     hint:"To cast a magical spell" },
  { id:84,  level:3, word:"UNIVERSE",  emoji:"🌌",  vowels:["U","I","E"],     consonants:["N","V","R","S"],     hint:"Everything that exists" },
  { id:85,  level:3, word:"ADVENTURE", emoji:"🗺️",  vowels:["A","E","U"],     consonants:["D","V","N","T","R"], hint:"An exciting journey" },
  { id:86,  level:3, word:"POWERFUL",  emoji:"⚡",  vowels:["O","E","U"],     consonants:["P","W","R","F","L"], hint:"Having great strength" },
  { id:87,  level:3, word:"CHAMPION",  emoji:"🏆",  vowels:["A","I","O"],     consonants:["C","H","M","P","N"], hint:"The winner" },
  { id:88,  level:3, word:"CONQUER",   emoji:"🏴",  vowels:["O","U","E"],     consonants:["C","N","Q","R"],     hint:"To defeat and take over" },
  { id:89,  level:3, word:"VICTORY",   emoji:"�",  vowels:["I","O"],         consonants:["V","C","T","R","Y"], hint:"Winning a battle" },
  { id:90,  level:3, word:"KINGDOM",   emoji:"👑",  vowels:["I","O"],         consonants:["K","N","G","D","M"], hint:"A land ruled by a king" },
  { id:91,  level:3, word:"TREASURE",  emoji:"💰",  vowels:["E","A","U"],     consonants:["T","R","S"],         hint:"Precious riches" },
  { id:92,  level:3, word:"COURAGE",   emoji:"🦁",  vowels:["O","U","A","E"], consonants:["C","R","G"],         hint:"Being brave in danger" },
  { id:93,  level:3, word:"POTION",    emoji:"🧪",  vowels:["O","I"],         consonants:["P","T","N"],         hint:"A magical liquid" },
  { id:94,  level:3, word:"PUZZLE",    emoji:"🧩",  vowels:["U","E"],         consonants:["P","Z","L"],         hint:"A game to solve" },
  { id:95,  level:3, word:"CANDLE",    emoji:"🕯️",  vowels:["A","E"],         consonants:["C","N","D","L"],     hint:"Burns with a flame" },
  { id:96,  level:3, word:"SPIDER",    emoji:"🕷️",  vowels:["I","E"],         consonants:["S","P","D","R"],     hint:"Spins a web" },
  { id:97,  level:3, word:"PALACE",    emoji:"🏛️",  vowels:["A","E"],         consonants:["P","L","C"],         hint:"A grand royal home" },
  { id:98,  level:3, word:"BANNER",    emoji:"🚩",  vowels:["A","E"],         consonants:["B","N","R"],         hint:"A flag or sign" },
  { id:99,  level:3, word:"ELIXIR",    emoji:"🍶",  vowels:["E","I"],         consonants:["L","X","R"],         hint:"A magical healing drink" },
  { id:100, level:3, word:"BOTTLE",    emoji:"🍾",  vowels:["O","E"],         consonants:["B","T","L"],         hint:"Holds a potion" }
];
